import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Header from "~/components/Header";
import Sidebar from "~/components/Sidebar";
import { ThemeProvider } from "~/providers/Theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <Sidebar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
